version: 0.2

phases:
  install:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t footcap .
      - docker tag footcap:latest 377250213022.dkr.ecr.ap-south-1.amazonaws.com/footcap:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 377250213022.dkr.ecr.ap-south-1.amazonaws.com/footcap:latest
      - echo Writing image definitions file...
      - printf '[{"name":"footcap","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
   
